version: "3.8"

services:
  web:
    build: ./app
    ports:
      - "8000:8000"
    command: bash -c 'cd /o-complex/ && alembic revision -m 'check' && alembic upgrade head  && uvicorn main:app --host 0.0.0.0 --port 8000 --reload'
    restart: always
    environment:
      - DB_PATH=postgresql+asyncpg://postgres:postgres@db:5432/o-complex-test-task
    depends_on:
      - db

  db:
    image: postgres
    ports:
    - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: o-complex-test-task